#!/usr/bin/env python3
"""
Refresh DL_F17_draft_points from all_drafts source data.
This script transforms raw draft picks into draft points for the algorithm.

Author: Generated by Claude
Date: 2026-01-26
"""

from google.cloud import bigquery
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

def refresh_draft_points():
    """Refresh DL_F17_draft_points from hockey.all_drafts"""

    client = bigquery.Client(project='prodigy-ranking')

    logger.info("=" * 80)
    logger.info("REFRESHING DL_F17_draft_points FROM all_drafts")
    logger.info("=" * 80)

    # Step 1: Create backup
    backup_timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    logger.info(f"Step 1: Creating backup...")

    backup_query = f"""
    CREATE OR REPLACE TABLE `prodigy-ranking.algorithm_core.DL_F17_draft_points_backup_{backup_timestamp}` AS
    SELECT * FROM `prodigy-ranking.algorithm_core.DL_F17_draft_points`
    """
    client.query(backup_query).result()
    logger.info(f"Backup created: DL_F17_draft_points_backup_{backup_timestamp}")

    # Step 2: Get current state
    logger.info("Step 2: Checking current state...")
    count_before = list(client.query("SELECT COUNT(*) as cnt FROM `prodigy-ranking.algorithm_core.DL_F17_draft_points`"))[0].cnt
    logger.info(f"Current records in DL_F17: {count_before}")

    # Step 3: Rebuild DL_F17_draft_points from all_drafts
    # This query:
    # - Joins all_drafts with player_stats to get current info
    # - Finds each player's best (lowest) draft pick
    # - Calculates points based on pick position
    # - Points formula: Pick 1 = 300, decreasing scale to pick 300+ = ~10

    logger.info("Step 3: Rebuilding DL_F17_draft_points...")

    rebuild_query = """
    CREATE OR REPLACE TABLE `prodigy-ranking.algorithm_core.DL_F17_draft_points` AS
    WITH draft_data AS (
        SELECT
            CAST(d.player_id AS INT64) as player_id,
            d.player_name,
            d.draft_league,
            d.overall_pick,
            d.team_name as draft_team,
            d.draft_year,
            ROW_NUMBER() OVER (PARTITION BY d.player_id ORDER BY d.overall_pick ASC) as pick_rank
        FROM `hockey-data-analysis.hockey.all_drafts` d
        WHERE d.player_id IS NOT NULL
        AND d.selection_made = TRUE
        AND d.player_name != 'No selection was made'
    ),
    best_picks AS (
        SELECT
            player_id,
            player_name,
            draft_league as best_draft_league,
            overall_pick as best_draft_pick,
            draft_team as best_draft_team,
            draft_year
        FROM draft_data
        WHERE pick_rank = 1  -- Best (lowest) pick for each player
    ),
    draft_counts AS (
        SELECT
            CAST(player_id AS INT64) as player_id,
            COUNT(*) as times_drafted
        FROM `hockey-data-analysis.hockey.all_drafts`
        WHERE player_id IS NOT NULL
        AND selection_made = TRUE
        GROUP BY player_id
    ),
    player_info AS (
        SELECT
            id as player_id,
            CONCAT(firstName, ' ', lastName) as player_name,
            position,
            yearOfBirth as year_of_birth,
            nationality_name as nationality,
            latestStats_team_name as current_team
        FROM `prodigy-ranking.algorithm_core.player_stats`
    )
    SELECT
        bp.player_id,
        COALESCE(pi.player_name, bp.player_name) as player_name,
        -- Points calculation: Pick 1 = 300, decreasing scale
        CAST(CASE
            WHEN bp.best_draft_pick = 1 THEN 300
            WHEN bp.best_draft_pick <= 10 THEN 300 - (bp.best_draft_pick - 1) * 5  -- Top 10: 300 to 255
            WHEN bp.best_draft_pick <= 30 THEN 255 - (bp.best_draft_pick - 10) * 3 -- 11-30: 252 to 195
            WHEN bp.best_draft_pick <= 60 THEN 195 - (bp.best_draft_pick - 30) * 2 -- 31-60: 193 to 135
            WHEN bp.best_draft_pick <= 100 THEN 135 - (bp.best_draft_pick - 60) * 1 -- 61-100: 134 to 95
            WHEN bp.best_draft_pick <= 200 THEN GREATEST(50, CAST(95 - (bp.best_draft_pick - 100) * 0.45 AS INT64)) -- 101-200: ~95 to 50
            ELSE GREATEST(10, CAST(50 - (bp.best_draft_pick - 200) * 0.2 AS INT64)) -- 201+: ~50 to 10
        END AS INT64) as points,
        bp.best_draft_league,
        bp.best_draft_pick,
        bp.best_draft_team,
        CASE
            WHEN bp.best_draft_pick <= 10 THEN 'Elite (Top 10)'
            WHEN bp.best_draft_pick <= 30 THEN 'High (Top 30)'
            WHEN bp.best_draft_pick <= 60 THEN 'Mid-High (Top 60)'
            WHEN bp.best_draft_pick <= 100 THEN 'Middle (Top 100)'
            WHEN bp.best_draft_pick <= 200 THEN 'Mid-Low (Top 200)'
            ELSE 'Low (200+)'
        END as best_draft_tier,
        dc.times_drafted,
        pi.current_team,
        pi.position,
        pi.year_of_birth,
        pi.nationality,
        TRUE as is_active,
        CURRENT_TIMESTAMP() as updated_at
    FROM best_picks bp
    LEFT JOIN draft_counts dc ON bp.player_id = dc.player_id
    LEFT JOIN player_info pi ON bp.player_id = pi.player_id
    WHERE bp.player_id IS NOT NULL
    """

    client.query(rebuild_query).result()
    logger.info("DL_F17_draft_points rebuilt successfully!")

    # Step 4: Verify results
    logger.info("Step 4: Verifying results...")

    count_after = list(client.query("SELECT COUNT(*) as cnt FROM `prodigy-ranking.algorithm_core.DL_F17_draft_points`"))[0].cnt
    logger.info(f"Records after rebuild: {count_after}")

    # Check Sawyer Thompson specifically
    sawyer_query = """
    SELECT player_id, player_name, points, best_draft_league, best_draft_pick, best_draft_team
    FROM `prodigy-ranking.algorithm_core.DL_F17_draft_points`
    WHERE player_id = 946038
    """
    sawyer_results = list(client.query(sawyer_query))

    if sawyer_results:
        logger.info(f"\nSawyer Thompson now in DL_F17:")
        for row in sawyer_results:
            logger.info(f"  Player ID: {row.player_id}")
            logger.info(f"  Name: {row.player_name}")
            logger.info(f"  Points: {row.points}")
            logger.info(f"  Best Draft: {row.best_draft_league} Pick #{row.best_draft_pick} ({row.best_draft_team})")
    else:
        logger.warning("Sawyer Thompson still not found in DL_F17!")

    # Summary by draft league
    summary_query = """
    SELECT
        best_draft_league,
        COUNT(*) as players,
        AVG(points) as avg_points,
        MIN(best_draft_pick) as best_pick,
        MAX(best_draft_pick) as worst_pick
    FROM `prodigy-ranking.algorithm_core.DL_F17_draft_points`
    GROUP BY best_draft_league
    ORDER BY players DESC
    """

    logger.info("\nSummary by draft league:")
    for row in client.query(summary_query):
        logger.info(f"  {row.best_draft_league}: {row.players} players, avg {row.avg_points:.0f} points, picks {row.best_pick}-{row.worst_pick}")

    logger.info("\n" + "=" * 80)
    logger.info("REFRESH COMPLETE!")
    logger.info("=" * 80)
    logger.info(f"Records: {count_before} -> {count_after} ({count_after - count_before:+d})")
    logger.info("\nNEXT STEP: Rebuild player_cumulative_points to propagate draft points to rankings")

    return count_after

if __name__ == "__main__":
    refresh_draft_points()
